image:
  - rocker/tidyverse
  - rocker/rstudio

stages:
  - build
  - deploy

build:
    stage: build
    variables:
        GITHUB_PAT: $GITHUB_PAT
    script:
        - R -e "remotes::install_deps(dependencies = c('Depends', 'Imports'))"
        - quarto render
    only:
        - main
    artifacts:
        paths:
            - public
        expire_in: 1 hr

deploy:
    image: node:latest
    stage: deploy
    before_script:
        - npm install netlify-cli
    script:
        - npx netlify deploy --prod --dir public
    only:
        - main
    dependencies:
        - build
